FROM node:16-alpine

WORKDIR /app/prod-site
COPY ./prod-site/package.json /app/prod-site
RUN npm install --legacy-peer-deps

COPY ./prod-site/ /app/prod-site

WORKDIR /app
COPY ./package.json /app
RUN npm install
COPY . /app

